--DDL   Data Definition Language

CREATE DATABASE Health_Clinic_Manha

USE Health_Clinic_Manha;

CREATE TABLE TipoDeUsuario
( IdTipoDeUsuario INT PRIMARY KEY IDENTITY,
  TituloTipoUsuario VARCHAR(20) NOT NULL UNIQUE
)

CREATE TABLE Usuario
( IdUsuario INT PRIMARY KEY IDENTITY,
  IdTipoDeUsuario INT FOREIGN KEY REFERENCES TipoDeUsuario(IdTipoDeUsuario)NOT NULL,
  Email VARCHAR(256) NOT NULL UNIQUE,
  Senha VARCHAR (100) NOT NULL
)

CREATE TABLE StatusConsulta
( IdStatusConsulta INT PRIMARY KEY IDENTITY,
  Situacao BIT DEFAULT(0)
)

CREATE TABLE Especialidade
( IdEspecialidade INT PRIMARY KEY IDENTITY,
  NomeEspecialidade VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Clinica
( IdClinica INT PRIMARY KEY IDENTITY,
  NomeFantasia VARCHAR(256) NOT NULL ,
  Endereco VARCHAR (256) NOT NULL,
  HorarioAbertura TIME NOT NULL,
  HorarioFechamento TIME NOT NULL,
  RazaoSocial VARCHAR (256) NOT NULL UNIQUE,
  CNPJ VARCHAR (14) NOT NULL UNIQUE
)

CREATE TABLE Paciente
( IdPaciente INT PRIMARY KEY IDENTITY,
  IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario)NOT NULL UNIQUE,
  Nome VARCHAR (256) NOT NULL,
  DataDeNascimento DATE NOT NULL,
  CPF CHAR(11) NOT NULL UNIQUE,
  Telefone VARCHAR (30) NOT NULL,
  CEP VARCHAR (9) NOT NULL,
  RG CHAR (9) NOT NULL UNIQUE
)

CREATE TABLE Medico
( IdMedico INT PRIMARY KEY IDENTITY,
  IdUsuario INT FOREIGN KEY REFERENCES Usuario(IdUsuario)NOT NULL UNIQUE,
  IdEspecialidade INT FOREIGN KEY REFERENCES Especialidade(IdEspecialidade)NOT NULL ,
  IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica)NOT NULL ,
  Nome VARCHAR(256) NOT NULL ,
  CRM VARCHAR (8) NOT NULL UNIQUE,
  Estado VARCHAR (30) NOT NULL
)

CREATE TABLE Consulta
( IdConsulta INT PRIMARY KEY IDENTITY,
  IdMedico INT FOREIGN KEY REFERENCES Medico(IdMedico)NOT NULL ,
  IdPaciente INT FOREIGN KEY REFERENCES Paciente(IdPaciente)NOT NULL ,
  IdStatusConsulta INT FOREIGN KEY REFERENCES StatusConsulta(IdStatusConsulta)NOT NULL ,
  DataConsulta DATE NOT NULL ,
  HorarioConsulta TIME  NOT NULL
)







